import { RequestPageRounded } from "@mui/icons-material";

const assets={
    img:{
        packDefoltImg:require('./image/image1.png'),
        notfoundImg:require('./image/notFound.png'),
        vector:require('./image/Vector.png')
    },
    svg:{
        tashrihiBoard:require('./svg/tashrihiboard.svg').default,
        testiBoard:require('./svg/testiBoard.svg').default,
        closeSvg:require('./svg/closeSvg.svg').default,
        uploadFile:require('./svg/Group 8921.svg').default,
        navBarIcon1:require('./svg/t1 2.svg').default,
        navBarIcon2:require('./svg/t1 3.svg').default,
        homeSvg:require('./svg/Group 13906.svg').default,
        porseshKhaneSvg:require('./svg/Group 13876.svg').default,
        searchSvg:require('./svg/searchSvg.svg').default,
        signupsvg:require('./svg/Group 13891.svg').default,
        twoManRunning:require('./svg/twoManRunning.svg').default,
        tikeSvg : require('./svg/Group 13897.svg').default,
        mainLandingSvg : require('./svg/Group 13910.svg').default,
        filterSearchSvg : require('./svg/Group 13873.svg').default,
        iconItem1 : require("./svg/Vector.svg").default,
        iconItem2 : require("./svg/Group 13928.svg").default,
        iconItem3 : require("./svg/Group 13929.svg").default,
        iconItem4 : require("./svg/Group 13930.svg").default,
        iconItem5 : require("./svg/Vector (1).svg").default,
        iconItem6 : require("./svg/Vector (2).svg").default,
        iconItem7 : require("./svg/Vector (3).svg").default,
        iconItem8 : require("./svg/Group 13927.svg").default,
        iconItem9 : require("./svg/Group 13924.svg").default,
        iconItem10 : require("./svg/Group 13923.svg").default,
        iconItem11 : require("./svg/Group 13925.svg").default,
        iconItem12 : require("./svg/Group 13926.svg").default,
        tikcardlanding : require("./svg/Group 8920.svg").default,
        littletikcartlanding : require("./svg/Vector 1.svg").default,
        simplecircle : require("./svg/Ellipse 67.svg").default,
        LandingStart : require("./svg/landingvector1.svg").default,
        LandingSakht : require("./svg/landingvector2.svg").default,
        Landingbargozari : require("./svg/landingvector3.svg").default,
        LandingKarname : require("./svg/landingvector4.svg").default,
        Landingtahlil : require("./svg/landingvector5.svg").default,
        landingline : require("./svg/Vector 110.svg").default,
        landingkarname1 : require("./svg/image 14.svg").default,
        landingkarname2 : require("./svg/image 17.svg") .default,
        landingperson1 : require("./svg/Group 13912.svg").default,
        landingperson2 : require("./svg/Group 13911.svg").default,
        landingperson3 : require("./svg/Group 13900.svg").default,
        landingwhytestaminofen : require("./svg/Group 13932.svg").default,
        landingtestalogo : require("./svg/Group 13937.svg").default,
        landingshadlogo : require("./svg/Group 151 (1).svg").default,
        landingtelegramlogo : require("./svg/Group 150.svg").default,
        landingbalelogo : require("./svg/Group 149.svg").default,
        landingeitalogo : require("./svg/Group 148.svg").default,
        landingaparatlogo : require("./svg/Group 147.svg").default,
        landinginstalogo : require("./svg/Group 146.svg").default,
        landingtelephone : require("./svg/Group 13938.svg").default,
        examAnjoman : require("./svg/Exams-amico.svg").default,

    }
}
export default assets;